# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: elasticsearch
    releaseName: elasticsearch
    repo: https://helm.elastic.co
    version: 8.5.1
    namespace: elasticsearch
    valuesFile: values.yaml